config/routes.rb
Rails.application.routes.draw do
  resources :slides
  root 'pages_controller#home'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
    has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController
  def home
    @slides = Slide.all
  end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/_navbar.html.erb
			<!-- Header -->
				<div id="header" class="alt">
					<div class="container">

                    <!-- NavLeft -->
                    <nav id="navleft">
                        <ul>
                    <li><a href="#one">A Zion</a></li>
					<li><a href="#">Galeria</a></li>
					<li><a href="#">Preços</a></li></ul>
                        </nav>
							
						<!-- Logo -->
                        <div id="logo">
							<%= link_to root_path do %>
							
							<%= image_tag("logo.png") %>
							
							<% end %>
                        </div>
						
						<!-- Nav -->
							<nav id="nav">
                                <ul>
					<li><a href="#">Eventos</a></li>
					<li><a href="#">Croquiteca</a></li>
					<li><a href="#">Contato</a></li>
								</ul>
							</nav>
                        
	
					</div>
                    
                        <a href="#menu">Menu</a>
				</div>
        
            <!-- Nav -->
                <nav id="menu">
                    <ul class="links">
                    <li><a href="#">A Zion</a></li>
					<li><a href="#">Galeria</a></li>
					<li><a href="#">Preços</a></li>
                    <li><a href="#">Eventos</a></li>
					<li><a href="#">Croquiteca</a></li>
					<li><a href="#">Contato</a></li>
                    </ul>
                </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
    
</body>
</html>

app/views/pages_controller/home.html.erb
<!-- Banner -->
			<section class="banner full">
				<article>
					<%= image_tag("slide01.jpg") %>
					<div class="inner">
						<header>
							<h2>Zion Escalada</h2>
							<p>A primeira academia de escalada indoor do Mato Grosso do Sul</p>
						</header>
					</div>
				</article>
				<article>
					<%= image_tag("slide02.jpg") %>
					<div class="inner">
						<header>
							<p>Lorem ipsum dolor sit amet nullam feugiat</p>
							<h2>Magna etiam</h2>
						</header>
					</div>
				</article>
				<article>
					<%= image_tag("slide03.jpg") %>
					<div class="inner">
						<header>
							<p>Sed cursus aliuam veroeros lorem ipsum nullam</p>
							<h2>Tempus dolor</h2>
						</header>
					</div>
				</article>
				<article>
					<%= image_tag("slide04.jpg") %>
					<div class="inner">
						<header>
							<p>Adipiscing lorem ipsum feugiat sed phasellus consequat</p>
							<h2>Etiam feugiat</h2>
						</header>
					</div>
				</article>
				<article>
					<%= image_tag("slide05.jpg") %>
					<div class="inner">
						<header>
							<p>Ipsum dolor sed magna veroeros lorem ipsum</p>
							<h2>Lorem adipiscing</h2>
						</header>
					</div>
				</article>
			</section>

		<!-- One -->
<section id="one" class="wrapper style2">
				<div class="inner">
					<header class="align-center">
						<h2>Sobre a Zion</h2>
						<p class="special"></p><br></br>
					</header>
					
					<div class="box">
						<div>
							<div class="content">
    <p><span class="image left"><%= image_tag("box1.jpg") %></span>
        
        A Zion é um ginásio de escalada em boulder indoor localizada em Campo Grande, MS.

Com vários níveis de dificuldade e técnica, para iniciantes e escaladores experientes. Temos como opção desenvolver um treinamento físico integrado com a escalada, acompanhado pelos nossos professores de educação física, através de uma forma dinâmica e eficiente.

A Zion Escalada Nasceu para promover a paixão da prática do montanhismo, através do encontro entre pessoas, natureza, esporte e aventura, de forma dinâmica e motivacional, voltando às nossas essências através da simplicidade, do bom humor e da alegria, respeitando sempre os limites individuais, o respeito ao próximo, a natureza, a segurança e a ética.</p>
								
							</div>
						</div>

					</div>
				</div>
			</section>
			


		<!-- Two -->
			<section id="two" class="wrapper style2">
				<div class="inner">
					<header class="align-center">
						<h2>Galeria</h2>
						<p class="special"></p><br></br>
					</header>
					<div class="container">
						<div class="popup-gallery">
						<% @slides.each do |slide| %>
							<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="img-fixed">
								<%= link_to slide.foto.url do %>
								<%= image_tag slide.foto.url(), class: "img-responsive" %>
								<% end %>
							</div>
						</div>
				        <% end %>
				        </div>
				       </div> 

				</div>
			</section>
			
			<!-- Three -->
			<section id="three" class="wrapper style2">
				<div class="inner">
					<header class="align-center">
						<h2><i class=""></i>Horários de Funcionamento</h2>
						<p class="special"></p><br></br>
					</header>
					<div class="row">
						
				        <div class="col-md-4 hbox">
				        	<div class="pricing hover-effect pbox">
								<div class="pricing-head">
									<h3><i class="icon fa-calendar"></i>  Segunda / Quarta / Sexta
									</h3>
									<span>Manhã</span>
									<h2><i class="icon fa-clock-o"></i> 08:30h às 11:20h
									</h2>
									<span>Tarde</span>
									<h2><i class="icon fa-clock-o"></i> 16:00h às 21:30h
									</h2>
								</div>
								</div>
				        </div>
				        <div class="col-md-4 hbox">
				        	<div class="pricing hover-effect pbox">
								<div class="pricing-head">
									<h3><i class="icon fa-calendar"></i>  Terça / Quinta
									</h3>
									<span>Tarde</span>
									<h2><i class="icon fa-clock-o"></i> 16:00h às 21:30h
									</h2>
								</div>
								</div>
				        </div>
				        <div class="col-md-4 hbox">
				        	<div class="pricing hover-effect pbox">
								<div class="pricing-head">
									<h3><i class="icon fa-plus"></i>  Zion Kids
									</h3>
									<span>Tarde</span>
									<h2><i class="icon fa-clock-o"></i> 16:00h às 17:30h
									</h2>
								</div>
								</div>
				        </div>
					</div>
				</div>
			</section>
			
			<!-- Four -->
			<section id="four" class="wrapper style2">
				<div class="inner">
					<header class="align-center">
						<h2><i class=""></i>Preços e Planos</h2>
						<p class="special"></p><br></br>
					</header>
					<div class="row">
						<!-- Pricing -->
						<div class="col-md-3">
							<div class="pricing hover-effect">
								<div class="pricing-head">
									<h3>Mensal
									</h3>
									<h4><i>R$</i>160<i>.00</i>
									</h4>
								</div>
								<ul class="pricing-content list-unstyled">
									<li>
										ESCALADA + MUSCULAÇÃO : R$ 250,00
									</li>
									<li>
										ESCALADA + NATAÇÃO : R$ 300,00
									</li>
									<li>
										ESCALADA CONVÊNIO : R$ 120,00
									</li>
									
								</ul>
							</div>
						</div>
						<div class="col-md-3">
							<div class="pricing hover-effect">
								<div class="pricing-head">
									<h3>Trimestral
									</h3>
									<h4><i>R$</i>140<i>.00</i>
									</h4>
								</div>
								<ul class="pricing-content list-unstyled">
									<li>
										ESCALADA + MUSCULAÇÃO : R$ 220,00
									</li>
									<li>
										ESCALADA + NATAÇÃO : R$ 265,00
									</li>
									<li>
										ESCALADA CONVÊNIO : R$ 105,00
									</li>
									
								</ul>
							</div>
						</div>
						<div class="col-md-3">
							<div class="pricing hover-effect">
								<div class="pricing-head">
									<h3>Semestral
									</h3>
									<h4><i>R$</i>120<i>.00</i>
									</h4>
								</div>
								<ul class="pricing-content list-unstyled">
									<li>
										ESCALADA + MUSCULAÇÃO : R$ 190,00
									</li>
									<li>
										ESCALADA + NATAÇÃO : R$ 240,00
									</li>
									<li>
										ESCALADA CONVÊNIO : R$ 90,00
									</li>
									
								</ul>
							</div>
						</div>
						<div class="col-md-3">
							<div class="pricing hover-effect">
								<div class="pricing-head">
									<h3>Anual
									</h3>
									<h4><i>R$</i>100<i>.00</i>
									</h4>
								</div>
								<ul class="pricing-content list-unstyled">
									<li>
										ESCALADA + MUSCULAÇÃO : R$ 160,00
									</li>
									<li>
										ESCALADA + NATAÇÃO : R$ 220,00
									</li>
									<li>
										ESCALADA CONVÊNIO : R$ 75,00
									</li>
									
								</ul>
							</div>
						</div>
		
					</div>
				</div>
		<!--//End Pricing -->
					</div>
				</div>
			</section>
			
			
			
			
			
			
			
			
			<script>
	$('.popup-gallery').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		mainClass: 'mfp-img-mobile',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
	});
</script>

app/views/slides/_form.html.erb
<section class="wrapper style2">
<%= form_for @slide, html: { multipart: true } do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.file_field :foto %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</section>

app/views/slides/edit.html.erb
<h1>Editing Slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slides</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
    
      <tr>
        <td><%= link_to slide.foto.url, class: "fancybox", :rel => 'group' do %>
            <%= image_tag slide.foto.url(:thumb) %>
            <% end %></td>
        <td><%= link_to 'Show', slide %></td>
        <td><%= link_to 'Edit', edit_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>